/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.mikebuyshouses.dncscrubber

import com.mikebuyshouses.dncscrubber.csvmanip.CSVSheetReader
import com.mikebuyshouses.dncscrubber.datamanip.DNCScrubber
import com.mikebuyshouses.dncscrubber.filemanip.DataWriterFactory
import com.mikebuyshouses.dncscrubber.models.BatchSkipTracingDataRowModel
import com.mikebuyshouses.dncscrubber.utils.CommandLineParser
import com.mikebuyshouses.dncscrubber.utils.FileUtils

class App {
    static void main(String[] args) {
        CommandLineParser parser = new CommandLineParser();
        parser.parseArgs(args);

        println "Reading in the CSV file '${parser.getInputFilename()}'..."
        List<BatchSkipTracingDataRowModel> csvData = new CSVSheetReader(BatchSkipTracingDataRowModel.class)
            .read(FileUtils.GetInputCsvFileName(parser.getInputFilename()));

        println "Scrubbing the DNC records...";
        List<BatchSkipTracingDataRowModel> scrubbedCsvData = new DNCScrubber().scrubCsvData(csvData);

        println "Outputting to output file '${parser.getOutputFilename()}'..."
        DataWriterFactory.GetDataWriter(FileUtils.GetFileExtension(parser.getOutputFilename()))
            .write(scrubbedCsvData, parser.getOutputFilename());

        println "All done!";
    }
}

