/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.mikebuyshouses.dncscrubber

import com.mikebuyshouses.dncscrubber.csvmanip.CSVSheetReader
import com.mikebuyshouses.dncscrubber.csvmanip.CSVSheetWriter
import com.mikebuyshouses.dncscrubber.datamanip.DNCScrubber
import com.mikebuyshouses.dncscrubber.filemanip.DataWriter
import com.mikebuyshouses.dncscrubber.filemanip.ExcelDataWriter
import com.mikebuyshouses.dncscrubber.models.BatchSkipTracingDataRowModel
import com.mikebuyshouses.dncscrubber.utils.CommandLineParser
import com.mikebuyshouses.dncscrubber.utils.FileUtils

class App {
    static void main(String[] args) {
        CommandLineParser parser = new CommandLineParser();
        parser.parseArgs(args);

        println "Reading in the CSV file '${parser.getInputFilename()}'..."
        List<BatchSkipTracingDataRowModel> csvData = new CSVSheetReader(BatchSkipTracingDataRowModel.class)
            .read(this.GetInputCsvFileName(parser));

        println "Scrubbing the DNC records...";
        List<BatchSkipTracingDataRowModel> scrubbedCsvData = new DNCScrubber().scrubCsvData(csvData);

        println "Outputting to output file '${parser.getOutputFilename()}'..."
        this.GetDataWriter(parser.getOutputFilename())
            .write(scrubbedCsvData, parser.getOutputFilename());

        println "All done!";
    }

    private static String GetInputCsvFileName(CommandLineParser parser) {
        if (parser.getInputFilename().endsWith(".csv"))
            return parser.getInputFilename();

        return FileUtils.ExcelToCsv(parser.getInputFilename())
                .getPath();
    }

    private static DataWriter GetDataWriter(String outputFileName) {
        final String fileExtension = outputFileName.substring(outputFileName.lastIndexOf('.') + 1);

        switch (fileExtension) {
            case "csv":
                return new CSVSheetWriter(BatchSkipTracingDataRowModel.class);
            case "xlsx":
                return new ExcelDataWriter();
        }

        throw new IllegalArgumentException("DataWriter for file with extension .'${fileExtension}' not yet implemented!")
    }
}

